//Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

//email Verification
export const EMAIL_VERIFICATION_REQUEST_SENT = 'EMAIL_VERIFICATION_REQUEST_SENT';
export const EMAIL_VERIFICATION_REQUEST_FAILED = 'EMAIL_VERIFICATION_REQUEST_FAILED';
export const EMAIL_VERIFICATION_CONFIRMED = 'EMAIL_VERIFICATION_CONFIRMED';
export const EMAIL_VERIFICATION_CONFIRM_FAILED = 'EMAIL_VERIFICATION_CONFIRM_FAILED';

//Password Reset
export const  FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const  FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const  RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';

//CUSTOMER PROFILE
 export const GET_CUSTOMER_PROFILE_SUCCESS ="GET_CUSTOMER_PROFILE_SUCCESS";
  export const GET_CUSTOMER_PROFILE_FAIL = "GET_CUSTOMER_PROFILE_FAIL";
  export const UPDATE_CUSTOMER_PROFILE_SUCCESS = "UPDATE_CUSTOMER_PROFILE_SUCCESS";
  export const UPDATE_CUSTOMER_PROFILE_FAIL = "UPDATE_CUSTOMER_PROFILE_FAIL";
  export const CLEAR_CUSTOMER_PROFILE = "CLEAR_CUSTOMER_PROFILE";
  export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS"
  export const GET_CUSTOMERS_FAIL = "GET_CUSTOMERS_FAIL"

//General
export const  SET_LOADING = 'SET_LOADING';
export const  CLEAR_ERRORS = 'CLEAR_ERRORS';
export const  SET_ERROR = 'SET_ERROR';

// Provider profile
export const GET_PROVIDER_PROFILE = 'GET_PROVIDER_PROFILE';
export const GET_PROVIDER_PROFILE_SUCCESS = 'GET_PROVIDER_PROFILE_SUCCESS';
export const GET_PROVIDER_PROFILE_FAIL = 'GET_PROVIDER_PROFILE_FAIL';
export const UPDATE_PROVIDER_PROFILE = 'UPDATE_PROVIDER_PROFILE';
export const UPDATE_PROVIDER_PROFILE_SUCCESS = 'UPDATE_PROVIDER_PROFILE_SUCCESS';
export const UPDATE_PROVIDER_PROFILE_FAIL = 'UPDATE_PROVIDER_PROFILE_FAIL';
export const UPLOAD_PROVIDER_PHOTO = 'UPLOAD_PROVIDER_PHOTO';
export const UPLOAD_PROVIDER_PHOTO_SUCCESS = 'UPLOAD_PROVIDER_PHOTO_SUCCESS';
export const UPLOAD_PROVIDER_PHOTO_FAIL = 'UPLOAD_PROVIDER_PHOTO_FAIL';
export const CLEAR_PROVIDER_PROFILE = 'CLEAR_PROVIDER_PROFILE';
export const PROVIDER_PROFILE_ERROR = 'PROVIDER_PROFILE_ERROR';
export const CLEAR_PROVIDERS = 'CLEAR_PROVIDERS';

// Provider listings
export const GET_PROVIDERS = 'GET_PROVIDERS';
export const GET_PROVIDERS_SUCCESS = 'GET_PROVIDERS_SUCCESS';
export const GET_PROVIDERS_FAIL = 'GET_PROVIDERS_FAIL';
export const SEARCH_PROVIDERS = 'SEARCH_PROVIDERS';
export const SEARCH_PROVIDERS_SUCCESS = 'SEARCH_PROVIDERS_SUCCESS';
export const SEARCH_PROVIDERS_FAIL = 'SEARCH_PROVIDERS_FAIL';
export const GET_PROVIDER = 'GET_PROVIDER';
export const GET_PROVIDER_FAIL = 'GET_PROVIDER_FAIL';

// Auth Message
export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';

// Provider Services
export const GET_PROVIDER_SERVICES_SUCCESS = 'GET_PROVIDER_SERVICES_SUCCESS';
export const GET_PROVIDER_SERVICES_FAIL = 'GET_PROVIDER_SERVICES_FAIL';
export const ADD_PROVIDER_SERVICE_SUCCESS = 'ADD_PROVIDER_SERVICE_SUCCESS';
export const ADD_PROVIDER_SERVICE_FAIL = 'ADD_PROVIDER_SERVICE_FAIL';
export const UPDATE_PROVIDER_SERVICE_SUCCESS = 'UPDATE_PROVIDER_SERVICE_SUCCESS';
export const UPDATE_PROVIDER_SERVICE_FAIL = 'UPDATE_PROVIDER_SERVICE_FAIL';
export const DELETE_PROVIDER_SERVICE_SUCCESS = 'DELETE_PROVIDER_SERVICE_SUCCESS';
export const DELETE_PROVIDER_SERVICE_FAIL = 'DELETE_PROVIDER_SERVICE_FAIL';
export const SET_SERVICES_LOADING = 'SET_SERVICES_LOADING';
export const CLEAR_SERVICE_ERROR = 'CLEAR_SERVICE_ERROR'; // For clearing errors

// Provider Statistics and Activity
export const GET_PROVIDER_STATS_SUCCESS = 'GET_PROVIDER_STATS_SUCCESS';
export const GET_PROVIDER_STATS_FAIL = 'GET_PROVIDER_STATS_FAIL';
export const STATS_LOADING = 'STATS_LOADING';
export const GET_PROVIDER_ACTIVITY_SUCCESS = 'GET_PROVIDER_ACTIVITY_SUCCESS';
export const GET_PROVIDER_ACTIVITY_FAIL = 'GET_PROVIDER_ACTIVITY_FAIL';
export const ACTIVITY_LOADING = 'ACTIVITY_LOADING';
export const CLEAR_PROVIDER_ERROR = 'CLEAR_PROVIDER_ERROR'; // General provider error clearing